### ISSUE TITLE
Playwright fails during the 'Building your Storybook' step with a "Command failed" error

### ISSUE THREAD

**Issue by ynotdraw** [chromaui/chromatic-cli#1097]
## Overview

I have a repository at https://github.com/ynotdraw/chromatic-testing to experiment with Chromatic.  My current requirement is to use Storybook to document the components, but rely on Playwright for the visual testing aspect. My Playwright tests spin up Storybook and run tests against the instance.

## Bug Report

When I run the recommended command locally in my CLI following the [documentation](https://www.chromatic.com/docs/playwright/#5-run-chromatic)...

```bash
pnpm chromatic --t=<MY_TOKEN_HERE> --playwright
```

I get no real error message, but a very long stack trace that is difficult to parse.

<details>

<summary>Log</summary>

```bash
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
  ✔ Authenticated with Chromatic
    → Using project token '********************'
  ✔ Retrieved git information
    → Commit '40894fc' on branch 'main'; no ancestor found
  ✔ Collected Storybook metadata
    → Storybook 8.1.11 for Web Components; using the @storybook/web-components-vite builder (8.1.11); supported addons found: Links, Essentials
  ✔ Initialized build
    → Build 16 initialized
  ✖ Building your Storybook
    → Command failed: node /workspace/chromatic-testing/node_modules/.pnpm/@chromatic-com+playwright@0.9.0_@babel+preset-env@7.24.7_@babel+c
…
    Publish your built Storybook
    Verify your Storybook
    Test your stories

    ✖ Failed to run `chromatic --playwright`:
    
    Command failed with exit code 1: node /workspace/chromatic-testing/node_modules/.pnpm/@chromatic-com+playwright@0.9.0_@babel+preset-env@7.24.7_@babel+core@7.24.7__@playwright+test_v57iekcqyjfnxbu3m7nmskwp5i/node_modules/@chromatic-com/playwright/dist/bin/build-archive-storybook.js --output-dir=/var/folders/pp/ss8llyp53j1bhwbbckdh6bmr0000gn/T/chromatic--49248-dOF2vr9YxGxe
node:internal/errors:863
const err = new Error(message);
            ^

Error: Command failed: node /workspace/chromatic-testing/node_modules/.pnpm/storybook@8.1.11_@babel+preset-env@7.24.7_@babel+core@7.24.7__react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/storybook/index.js build --output-dir=/var/folders/pp/ss8llyp53j1bhwbbckdh6bmr0000gn/T/chromatic--49248-dOF2vr9YxGxe -c /workspace/chromatic-testing/node_modules/.pnpm/@chromatic-com+playwright@0.9.0_@babel+preset-env@7.24.7_@babel+core@7.24.7__@playwright+test_v57iekcqyjfnxbu3m7nmskwp5i/node_modules/@chromatic-com/playwright/dist/storybook-config
  at checkExecSyncError (node:child_process:885:11)
  at Object.execFileSync (node:child_process:921:15)
  at /workspace/chromatic-testing/node_modules/.pnpm/@chromatic-com+playwright@0.9.0_@babel+preset-env@7.24.7_@babel+core@7.24.7__@playwright+test_v57iekcqyjfnxbu3m7nmskwp5i/node_modules/@chromatic-com/playwright/dist/bin/build-archive-storybook.js:15:2609 {
status: 1,
signal: null,
output: [ null, null, null ],
pid: 49292,
stdout: null,
stderr: null
}

Node.js v19.1.0
```

</details>

My first thought was maybe there's an issue with building and serving Storybook.  That's not the case. When I run `pnpm build-storybook` locally, the build succeeds. I can also run `pnpm start` just fine and have Storybook pull up, while also serving storybook via `npx http-server ./storybook-static/ `.  So I'm not sure why Chromatic is having an issue with it.

When running the Chromatic command, I do get a `build-storybook.log` file that may be helpful.

<details>

<summary>build-storybook.log</summary>

```bash
@storybook/cli v8.1.11

info => Cleaning outputDir: ../../../../var/folders/pp/ss8llyp53j1bhwbbckdh6bmr0000gn/T/chromatic--49248-dOF2vr9YxGxe
info => Loading presets
Error: Cannot find module 'storybook/internal/core-events'
Require stack:
- ./node_modules/.pnpm/@storybook+builder-webpack5@8.3.5_esbuild@0.20.2_storybook@8.1.11_@babel+preset-env@7.24.7_@b_mzfnnelg6qwxte4ki5eqywo6pa/node_modules/@storybook/builder-webpack5/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Module._load (node:internal/modules/cjs/loader:872:27)
    at Module.require (node:internal/modules/cjs/loader:1092:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (./node_modules/.pnpm/@storybook+builder-webpack5@8.3.5_esbuild@0.20.2_storybook@8.1.11_@babel+preset-env@7.24.7_@b_mzfnnelg6qwxte4ki5eqywo6pa/node_modules/@storybook/builder-webpack5/dist/index.js:1:2793)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Object.newLoader (./node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.20.2/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (./node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.20.2/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1068:32)

```

</details>

## Reproduction Steps

1. Pull down the repository at https://github.com/ynotdraw/chromatic-testing
2. I'm currently using `Node.js v19.1.0` and `pnpm@9.4.0`
3. Run `pnpm i`
4. Run `pnpm build-storybook`
5. Run `pnpm chromatic --t=<MY_TOKEN_HERE> --playwright`, replacing your `<MY_TOKEN_HERE>` with a real token from Chromatic
6. Notice the error in your console

**Comment by ynotdraw** [comment]
Hey @jmhobbs thanks so much for responding so quickly. I really appreciate it!

After your message, I ended up [bumping the storybook dependencies](https://github.com/ynotdraw/chromatic-testing/commit/b67052a953cde665ed5d04d4d09bb818d5aa73a8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) and now things are passing! Apologies for not trying that first - I was confused as to why this was only failing for Chromatic's run, but not when I ran Storybook directly, so I didn't think it could've been a Storybook bug.

Thanks a bunch for the information and help! 🙇
