### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-loader'

### ISSUE THREAD

**Issue by Hongbo-Miao** [chromaui/chromatic-cli#15]
Chromatic works all time before, but this time got the error below.
Tried to rerun the Travis job, got same error.

This is a log copy from https://travis-ci.com/Hongbo-Miao/hongbomiao.com/jobs/237302067 for this [pull request](https://github.com/Hongbo-Miao/hongbomiao.com/pull/204).

Sorry it is a little bit long. I copied here in case the log got wiped later.

```bash
$ chromatic test
WARNING: Running Chromatic on a Travis PR build from an internal branch.
It is recommended to run Chromatic on the push builds from Travis where possible.
We advise turning on push builds and disabling Chromatic for internal PR builds.
Read more: https://docs.chromaticqa.com/setup_ci#travis

Chromatic: Building your Storybook
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ build-storybook -s public -o /tmp/chromatic-5620VnzEfNQp8j96 --loglevel error
(node:5655) UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-loader'
Require stack:
- /home/travis/build/Hongbo-Miao/hongbomiao.com/.storybook/webpack.config.js
- /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/utils/server-require.js
- /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/common/custom-presets.js
- /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/config.js
- /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/build-static.js
- /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/server.js
- /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/react/dist/server/build.js
- /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/react/bin/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19)
    at module.exports (/home/travis/build/Hongbo-Miao/hongbomiao.com/.storybook/webpack.config.js:4:21)
    at Object.webpack (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:56:12)
(node:5655) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5655) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Chromatic: Uploading your built Storybook...
Chromatic: Uploaded your build, verifying
Chromatic: Uploading and verifying build (this may take a few minutes depending on your connection)
**Chromatic build failed. Please note the session id: '4b6a9163-23f8-425f-86b9-b5ed039c1039' and contact support@hichroma.com -or- open a support ticket at https://chromaticqa.com**
StatusCodeError: 404 - {"type":"Buffer","data":[52,48,52]}
    at new StatusCodeError (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/request/request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.<anonymous> (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:209:13)
    at IncomingMessage.<anonymous> (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:298:28)
    at IncomingMessage.emit (events.js:214:15) {
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - {"type":"Buffer","data":[52,48,52]}',
  error: <Buffer 34 30 34>,
  options: {
    resolveWithFullResponse: true,
    encoding: null,
    gzip: true,
    headers: {
      'User-Agent': 'Chromatic',
      Referer: undefined,
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      'Accept-Language': 'en'
    },
    jar: RequestJar { _jar: [CookieJar] },
    uri: 'https://5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com/iframe.html',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    transform2xxOnly: false
  },
  response: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: true,
      decoder: null,
      encoding: null
    },
    readable: false,
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function],
      error: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: '5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: '5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 1550,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: '5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: '5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 1550,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      server: 'nginx/1.17.3',
      date: 'Thu, 19 Sep 2019 18:17:47 GMT',
      'content-length': '3',
      connection: 'close'
    },
    rawHeaders: [
      'Server',
      'nginx/1.17.3',
      'Date',
      'Thu, 19 Sep 2019 18:17:47 GMT',
      'Content-Length',
      '3',
      'Connection',
      'close'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 404,
    statusMessage: 'Not Found',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: '5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: '5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 1550,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /iframe.html HTTP/1.1\r\n' +
        'User-Agent: Chromatic\r\n' +
        'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n' +
        'Accept-Language: en\r\n' +
        'host: 5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com\r\n' +
        'accept-encoding: gzip, deflate\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/iframe.html',
      _ended: true,
      res: [Circular],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      resolveWithFullResponse: true,
      encoding: null,
      gzip: true,
      headers: [Object],
      uri: [Url],
      readable: true,
      writable: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      _rp_resolve: [Function],
      _rp_reject: [Function],
      _rp_promise: [Promise],
      _rp_callbackOrig: undefined,
      callback: [Function],
      _rp_options: [Object],
      setHeader: [Function],
      hasHeader: [Function],
      getHeader: [Function],
      removeHeader: [Function],
      method: 'GET',
      localAddress: undefined,
      pool: {},
      dests: [],
      __isRequestRequest: true,
      _callback: [Function: RP$callback],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _jar: [RequestJar],
      port: 443,
      host: '5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com',
      path: '/iframe.html',
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com/iframe.html',
      req: [ClientRequest],
      ntick: true,
      response: [Circular],
      originalHost: '5d626a63a601530020759b10-fwbijeyauj.tunnel.chromaticqa.com',
      originalHostHeaderName: 'host',
      responseContent: [Circular],
      _destdata: true,
      _ended: true,
      _callbackCalled: true
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: <Buffer 34 30 34>
  }
}
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "CHROMATIC_APP_CODE=$CHROMATIC_APP_CODE yarn run chromatic" exited with 255.
```

**Comment by Hongbo-Miao** [comment]
Another PR https://github.com/Hongbo-Miao/hongbomiao.com/pull/207 has exactly same change, Chromatic works this time without any error.

**Comment by tmeasday** [comment]
@Hongbo-Miao thanks for the report. It looks like your storybook has failed to build properly thanks to a missing dependency (`babel-loader`).

I'm not sure why that's happened by perhaps you should try running `yarn build-storybook` locally and see if that works?

**Comment by Hongbo-Miao** [comment]
@tmeasday it is a little hard to debug after several new chromatic related commits got merged. I will try to reproduce if next time happens again. Thanks!

**Comment by Hongbo-Miao** [comment]
Hi @tmeasday I got same [error](https://travis-ci.com/Hongbo-Miao/hongbomiao.com/jobs/260005982) again after this [pull request](https://github.com/Hongbo-Miao/hongbomiao.com/pull/362) which upgrading

@babel/preset-env 7.7.1 -> 7.7.4
@babel/preset-typescript 7.7.2 -> 7.7.4

> $ chromatic test
> chromatic info Building your Storybook 
> warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
> $ build-storybook -s public -o /tmp/chromatic-5517uJJWPYoJiz7H --loglevel error
> (node:5554) UnhandledPromiseRejectionWarning: Error: Cannot find module 'babel-loader'
> Require stack:
> - /home/travis/build/Hongbo-Miao/hongbomiao.com/.storybook/webpack.config.js
> - /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/utils/server-require.js
> - /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/common/custom-presets.js
> - /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/config.js
> - /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/build-static.js
> - /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/server.js
> - /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/react/dist/server/build.js
> - /home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/react/bin/build.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
>     at Function.resolve (internal/modules/cjs/helpers.js:80:19)
>     at module.exports (/home/travis/build/Hongbo-Miao/hongbomiao.com/.storybook/webpack.config.js:4:21)
>     at Object.webpack (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:56:12)
>     at async buildPreview (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/build-static.js:192:25)
>     at async buildStaticStandalone (/home/travis/build/Hongbo-Miao/hongbomiao.com/node_modules/@storybook/core/dist/server/build-static.js:246:3)
> (node:5554) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:5554) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> chromatic info Uploading your built Storybook... 

![image](https://user-images.githubusercontent.com/3375461/69929432-fb139c00-14f9-11ea-92e3-e96a81a89d00.png)

**Comment by Hongbo-Miao** [comment]
Also, it might related with https://github.com/storybookjs/storybook/issues/4672

**Comment by tmeasday** [comment]
This looks to be a storybook problem rather than a chromatic one, per se.

**Comment by Hongbo-Miao** [comment]
Hmm, I think so. I will close this for now. Thanks!
