### ISSUE TITLE
Better issue when git log fails

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#22]
The error is in there if you look but:

(a) people get distracted by all the line noise
(b) the actually output of the git failure is in buffer form so not really readable.

E.g.:

```
$ chromatic test --build-script-name build:storybook
**Chromatic build failed. Please note the session id: '986d907b-538b-4e0b-936e-147ebae7fa80' and contact support@hichroma.com -or- open a support ticket at https://chromaticqa.com**

{ Error: Command failed: git log -n 1 --format="%H,%ct,%ce,%cn" 2>&1
at checkExecSyncError (child_process.js:629:11)
at execSync (child_process.js:666:13)
at /builds/greenberrynl/povo/storybook/node_modules/storybook-chromatic/dist/tester.js:1:18063
at tryCatch (/builds/greenberrynl/povo/storybook/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
at Generator.invoke [as _invoke] (/builds/greenberrynl/povo/storybook/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
at Generator.prototype.(anonymous function) [as next] (/builds/greenberrynl/povo/storybook/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
at asyncGeneratorStep (/builds/greenberrynl/povo/storybook/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (/builds/greenberrynl/povo/storybook/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
at /builds/greenberrynl/povo/storybook/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
at new Promise (<anonymous>)
status: 127,
signal: null,
output:
[ null,
<Buffer 2f 62 69 6e 2f 73 68 3a 20 31 3a 20 67 69 74 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>,
<Buffer > ],
pid: 50,
stdout:
<Buffer 2f 62 69 6e 2f 73 68 3a 20 31 3a 20 67 69 74 3a 20 6e 6f 74 20 66 6f 75 6e 64 0a>,
stderr: <Buffer > }

error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Job failed: exit code 1
```

**Comment by tmeasday** [comment]
Also we should be explicit about the two common failures:

Git not installed
Git binary available but .git folder missing
