### ISSUE TITLE
Unhandled promise rejection: Flag keys may not contain '-'

### ISSUE THREAD

**Issue by Greg-mso** [chromaui/chromatic-cli#236]
Hi,

When trying to run chromatic I am receiving the following error:

`Unhandled promise rejection: Flag keys may not contain '-': project-token, app-code, build-script-name, output-dir, storybook-build-dir, allow-console-errors, auto-accept-changes, exit-once-uploaded, exit-zero-on-changes, ignore-last-build-on-branch, patch-build, preserve-missing, junit-report, do-not-start, script-name, storybook-port, storybook-url, storybook-https, storybook-cert, storybook-key, storybook-ca
Error: Flag keys may not contain '-': project-token, app-code, build-script-name, output-dir, storybook-build-dir, allow-console-errors, auto-accept-changes, exit-once-uploaded, exit-zero-on-changes, ignore-last-build-on-branch, patch-build, preserve-missing, junit-report, do-not-start, script-name, storybook-port, storybook-url, storybook-https, storybook-cert, storybook-key, storybook-ca
    at validateOptions (XXXX/node_modules/chromatic/node_modules/meow/index.js:61:9)
    at meow (XXXX/node_modules/chromatic/node_modules/meow/index.js:136:2)
    at parseArgs (XXXX/node_modules/chromatic/bin/lib/parseArgs.js:4:39)
    at Proxy.main (XXXX/node_modules/chromatic/bin/main.js:32:67)`

I am running Chromatic 5.5.0 ( have also tried 5.2.0 ) + storybook 6.1.11. 
Thanks.

**Comment by Greg-mso** [comment]
Beaten to raising it :) #235
