### ISSUE TITLE
When I rename a directory, chromatic-deployment errors out when it can’t find a directory with the old name

### ISSUE THREAD

**Issue by brandondurham** [chromaui/chromatic-cli#394]
I renamed the `src/components/PointAccount/` directory to `src/components/AccountCard/`. When I pushed the change to GitHub, The `chromatic-deployment` workflow runs and errors out with this:

```bash
ModuleNotFoundError: Module not found: Error: Can't resolve '.' in '/home/runner/work/component-library/component-library/src/components/PointAccount'
```

**Comment by brandondurham** [comment]
Sure thing!

When pushing to any branch in GitHub, **[this action](https://github.com/chromaui/action)** is run. It fails on the `build-storybook` step with this output:

```bash
Run chromaui/action@v1
  with:
    token: ***
    projectToken: ***
  env:
    STORYBOOK_GOOGLE_PLACES_API_KEY: ***
    STORYBOOK_STRIPE_API_KEY: ***

Chromatic CLI v5.9.2
chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to index.chromatic.com
Authenticated with Chromatic
    → Using project token '********73d5'
Retrieving git information
Retrieved git information
    → Commit 'c070257' on branch 'feature/bdurham/ch987/confirmation-prompt-small-modal'; found 1 parent commit
Collecting Storybook metadata
Collected Storybook metadata
    → Storybook v6.3.6 for React; supported addons found: A11y, Actions, Essentials, Links
Building your Storybook
    → Running command: npm run --silent build-storybook -- --output-dir /tmp/chromatic--2033-YVBlMu1ZKmsh
The CLI tried to run your build-storybook script, but the command failed. This indicates a problem with your Storybook. Here's what to do:

- Check the Storybook build log printed below.
- Run npm run build-storybook or yarn build-storybook yourself and make sure it outputs a valid Storybook by opening the generated index.html in your browser.
- Review the build-storybook CLI options at storybook.js.org/docs/configurations/cli-options/#for-build-storybook

Command failed with exit code 1: npm run --silent build-storybook -- --output-dir /tmp/chromatic--2033-YVBlMu1ZKmsh

ℹ Spawn settings:
{
  "client": "npm",
  "clientVersion": "6.14.14",
  "nodeVersion": "v14.17.5",
  "platform": "linux",
  "command": "npm",
  "clientArgs": [
    "run",
    "--silent"
  ],
  "scriptArgs": [
    "build-storybook",
    "--",
    "--output-dir",
    "/tmp/chromatic--2033-YVBlMu1ZKmsh"
  ]
}

ℹ Storybook build output:
/home/runner/work/component-library/component-library/build-storybook.log

info @storybook/react v6.3.6
info 
info => Cleaning outputDir: /tmp/chromatic--2033-YVBlMu1ZKmsh
info => Copying static files: ././.storybook/static => ./
info => Loading presets
info => Loading custom manager config
info => Compiling manager..
info => Compiling preview..
info => Loading 1 config file in "/home/runner/work/component-library/component-library/.storybook"
info => Loading 11 other files in "/home/runner/work/component-library/component-library/.storybook"
info => Loading custom manager config
info => Adding stories defined in "/home/runner/work/component-library/component-library/.storybook/main.js"
info => Using implicit CSS loaders
info => Using default Webpack4 setup
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve '.' in '/home/runner/work/component-library/component-library/src/components/PointAccount'
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve '.' in '/home/runner/work/component-library/component-library/src/components/PointAccount'
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/Compilation.js:925:10
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/NormalModuleFactory.js:401:22
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/NormalModuleFactory.js:130:21
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/NormalModuleFactory.js:224:22
ERR!     at /home/runner/work/component-library/component-library/node_modules/neo-async/async.js:2830:7
ERR!     at /home/runner/work/component-library/component-library/node_modules/neo-async/async.js:6877:13
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/NormalModuleFactory.js:214:25
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/Resolver.js:213:14
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/Resolver.js:285:5
ERR!     at eval (eval at create (/home/runner/work/component-library/component-library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/Resolver.js:285:5
ERR!     at eval (eval at create (/home/runner/work/component-library/component-library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/Resolver.js:285:5
ERR!     at eval (eval at create (/home/runner/work/component-library/component-library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
ERR!  ModuleNotFoundError: Module not found: Error: Can't resolve '.' in '/home/runner/work/component-library/component-library/src/components/PointAccount'
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/Compilation.js:925:10
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/NormalModuleFactory.js:401:22
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/NormalModuleFactory.js:130:21
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/NormalModuleFactory.js:224:22
ERR!     at /home/runner/work/component-library/component-library/node_modules/neo-async/async.js:2830:7
ERR!     at /home/runner/work/component-library/component-library/node_modules/neo-async/async.js:6877:13
ERR!     at /home/runner/work/component-library/component-library/node_modules/webpack/lib/NormalModuleFactory.js:214:25
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/Resolver.js:213:14
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/Resolver.js:285:5
ERR!     at eval (eval at create (/home/runner/work/component-library/component-library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/Resolver.js:285:5
ERR!     at eval (eval at create (/home/runner/work/component-library/component-library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/Resolver.js:285:5
ERR!     at eval (eval at create (/home/runner/work/component-library/component-library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
ERR!     at /home/runner/work/component-library/component-library/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
ERR! resolve '.' in '/home/runner/work/component-library/component-library/src/components/PointAccount'
ERR!   using description file: /home/runner/work/component-library/component-library/package.json (relative path: ./src/components/PointAccount)
ERR!     Field 'browser' doesn't contain a valid alias configuration
ERR!     using description file: /home/runner/work/component-library/component-library/package.json (relative path: ./src/components/PointAccount)
ERR!       no extension
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         /home/runner/work/component-library/component-library/src/components/PointAccount is not a file
ERR!       .js
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         /home/runner/work/component-library/component-library/src/components/PointAccount.js doesn't exist
ERR!       .svg
ERR!         Field 'browser' doesn't contain a valid alias configuration
ERR!         /home/runner/work/component-library/component-library/src/components/PointAccount.svg doesn't exist
ERR!       as directory
ERR!         existing directory
ERR!           using path: /home/runner/work/component-library/component-library/src/components/PointAccount/index
ERR!             using description file: /home/runner/work/component-library/component-library/package.json (relative path: ./src/components/PointAccount/index)
ERR!               no extension
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 /home/runner/work/component-library/component-library/src/components/PointAccount/index doesn't exist
ERR!               .js
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 /home/runner/work/component-library/component-library/src/components/PointAccount/index.js doesn't exist
ERR!               .svg
ERR!                 Field 'browser' doesn't contain a valid alias configuration
ERR!                 /home/runner/work/component-library/component-library/src/components/PointAccount/index.svg doesn't exist
    → Command failed: npm run --silent build-storybook -- --output-dir /tmp/chromatic--2033-YVBlMu1ZKmsh




Error: non-zero exit code
```
Is there anything else I can share that might help debug?

Thank yoU!!

**Comment by brandondurham** [comment]
🤦🏻‍♂️

Please excuse my ignorance. Turns out there was still a stray file in the `PointAccounts` directory trying to load `.`. Removed and it works.

Sorry to waste your time.

**Comment by tmeasday** [comment]
All good @brandondurham
