### ISSUE TITLE
"Invalid or unexpected token" with appropriate token

### ISSUE THREAD

**Issue by kylesuss** [chromaui/chromatic-cli#445]
I've had a few reports come through in support of people getting this feedback:

```
npx chromatic --project-token=<token>
Invalid or unexpected token
```

The token matches what I expect for their project. Someone on support told me that downgrading the CLI fixes the issue but it wasn't clear which version introduced the problem.

**Comment by joshuafranks** [comment]
I was facing this issue when trying to publish a project for the first time and spoke to one of your support guys. They suggested downgrading to `5.6.2`, which seems to have fixed the issue for me :+1:

**Comment by joshuafranks** [comment]
I've tried checking out the tags `6.0.2` through `6.0.5` and had no luck. If I try it with `6.0.0`, I see some additional details.

Hope this helps:

```
SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.f.f.require (/home/joshuafranks/code/ssr-container-prototype/node_modules/chromatic/bin/main.cjs:2:11023)
    at Promise.all.Object.keys.reduce (/home/joshuafranks/code/ssr-container-prototype/node_modules/chromatic/bin/main.cjs:2:10319)
    at Array.reduce (<anonymous>)
(node:64343) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by ghengeveld** [comment]
This issue was traced back to Node itself. The error has nothing to do with the Chromatic project token, it's about an invalid character (aka "token"). If you encounter this issue, try upgrading your Node.js version.

**Comment by sshaw** [comment]
Upgrading from Node.js v10 (😬) worked for me!
