### ISSUE TITLE
HTTPClient failed to fetch https://index.chromatic.com/graphql, got 400/Bad Request

### ISSUE THREAD

**Issue by perevezencev** [chromaui/chromatic-cli#507]
We are using Github Action chromaui/action@v1, when run we get the following error:
```
Error: ✖ Failed to verify your Storybook
HTTPClient failed to fetch https://index.chromatic.com/graphql, got 400/Bad Request
    at l.retries (/home/runner/work/_actions/chromaui/action/v1/action/main.js:2:34244)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async l.retries (/home/runner/work/_actions/chromaui/action/v1/action/main.js:2:34830)
    at async rt.steps (/home/runner/work/_actions/chromaui/action/v1/action/main.js:198:4463)
    at async e.exports.task (/home/runner/work/_actions/chromaui/action/v1/action/main.js:15:1832)
```
Full logs [here](https://github.com/kaluga-astral/frontend/runs/4921783824?check_suite_focus=true)

**Comment by tmeasday** [comment]
@ghengeveld so the error here is:

> Field "committedAt" of required type "Float!" was not provided.

@perevezencev the reason for this error is logged as a warning in your build logs:

```
⚠ Commit 5ac171f does not exist
We tried to retrieve the commit details but couldn't find it in your Git history.
Check your CHROMATIC_SHA environment variable.
Continuing with just the commit hash.
```

I am not sure what is causing this situation. @ghengeveld I note @perevezencev is using the `checkout@v2` action with `fetchDepth: 0`

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
