### ISSUE TITLE
How to diagnose test errors?

### ISSUE THREAD

**Issue by ZebraFlesh** [chromaui/chromatic-cli#533]
I'm seeing this error when I run chromatic:
```
Error: Evaluation failed: TypeError: Cannot read property 'template' of null
    at wrapper (https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/538.48fd0bf1.iframe.bundle.js:2:2269575)
    at https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/538.48fd0bf1.iframe.bundle.js:2:379066
    at https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/538.48fd0bf1.iframe.bundle.js:2:379296
    at https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/538.48fd0bf1.iframe.bundle.js:2:367966
    at https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/538.48fd0bf1.iframe.bundle.js:2:810555
    at https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/538.48fd0bf1.iframe.bundle.js:2:810300
    at wrapper (https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/main.8fdb9164.iframe.bundle.js:1:19408)
    at https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/538.48fd0bf1.iframe.bundle.js:2:379066
    at https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/538.48fd0bf1.iframe.bundle.js:2:379296
    at https://6216b6b604f906003a0aa651-vstnglpfac.chromatic.com/538.48fd0bf1.iframe.bundle.js:2:367966
    at ExecutionContext._evaluateInternal (/var/task/capture-v3/build/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/var/task/capture-v3/build/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async /var/task/capture-v3/build/bundle.js:615293:7
    at async NavigatorWatcher2.waitForIdle (/var/task/capture-v3/build/bundle.js:608628:9)
    at async PuppeteerRenderer.renderSpec (/var/task/capture-v3/build/bundle.js:615254:25)
    at async PuppeteerRenderer.renderSnapshot (/var/task/capture-v3/build/bundle.js:615157:21)
    at async PuppeteerRenderer.captureSpecs (/var/task/capture-v3/build/bundle.js:615106:18)
    at async PuppeteerRenderer.executeWithCallback (/var/task/capture-v3/build/bundle.js:615348:14)
    at async Capture.execute (/var/task/capture-v3/build/bundle.js:615615:5)
```

How can I go about diagnosing what's going on here? The Troubleshooting section of the docs says:

> A build will fail if any of the snapshots fail to render (i.e. in rendering the latest version of the component, the snapshot throws a JavaScript exception). You’ll need to fix the code for errored components before we can pass the build.

The story in question renders without any errors in storybook, so I'm puzzled as to what's going on, how to find the problem, and how to fix it.

**Comment by ZebraFlesh** [comment]
Resolved: click the "Open storybook" link in the stack trace page and you'll get better/different information.
