### ISSUE TITLE
Cannot redefine property: __esModule

### ISSUE THREAD

**Issue by bonesoul** [chromaui/chromatic-cli#597]
publishing fails lately for my project:

```
TypeError: Cannot redefine property: __esModule
    at Function.defineProperty (<anonymous>)
    at Object../.storybook/preview.js-generated-config-entry.js (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:2024)
    at __webpack_require__ (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/runtime~main.da7e426a.iframe.bundle.js:1:381)
    at __webpack_exec__ (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:323746)
    at https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:325154
    at Function.__webpack_require__.O (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/runtime~main.da7e426a.iframe.bundle.js:1:987)
    at https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:325297
    at webpackJsonpCallback (https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/runtime~main.da7e426a.iframe.bundle.js:1:6189)
    at https://6220ba09a126ca003f1d9a5b-mjilyunzup.capture.chromatic.com/main.7fe25a90.iframe.bundle.js:1:83
    → Failed to publish build
```

**Comment by bonesoul** [comment]
hi there,

it was an error caused my own storybook configuration. please discard this issue.

**Comment by sibStephen** [comment]
@bonesoul  hwat was the missing config ? Facing the same issue on my local as well.
