### ISSUE TITLE
Can I run a patch build in chromatic CLI with using SSH for connection to git@github

### ISSUE THREAD

**Issue by re-taro** [chromaui/chromatic-cli#626]
when I run
```
npx chromatic --project-token="token" --patch-build=feature/#61...dev
```

in the console there is some error
```
Chromatic CLI v6.7.3
https://www.chromatic.com/docs/cli

  / Preparing your workspace
    → Installing dependencies
    Authenticate
    Retrieve git information
    Collect Storybook metadata
    Initialize build
    Build Storybook
    Publish your built Storybook
    Verify your Storybook
    Test your stories
    Restore workspace
Error: Command failed with exit code 1: git remote update
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at e.exports (D:\repository\2022-HP\node_modules\chromatic\bin\main.cjs:3:502299)
    at D:\repository\2022-HP\node_modules\chromatic\bin\main.cjs:3:499477
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I probably think using SSH to connect makes wrong.
What should I do?

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
