### ISSUE TITLE
TurboSnap fails when trying to trace internal monorepo package

### ISSUE THREAD

**Issue by jaknas** [chromaui/chromatic-cli#707]
**Bug report**

After enabling TurboSnap, I'm seeing this error:
```
 {"rootPath":"/home","manifestPath":"packages/foo/package.json","lockfilePath":"yarn.lock"} Failed to get dependencies

 {"name":"OutOfSyncError","message":"Dependency @acme/bar was not found in yarn.lock. Your package.json and yarn.lock are probably out of sync. Please run \"yarn install\" and try again.","stack":"OutOfSyncError: Dependency @acme/bar was not found in yarn.lock. Your package.json and yarn.lock are probably out of sync. Please run \"yarn install\" and try again.\n    at c.getDependencyTree (/home/node_modules/chromatic/bin/main.cjs:425:66293)\n    at runNextTicks (internal/process/task_queues.js:60:5)\n    at processImmediate (internal/timers.js:437:9)\n    at async c.getDependencyTree (/home/node_modules/chromatic/bin/main.cjs:425:70445)\n    at async t.buildDepTreeFromFiles (/home/node_modules/chromatic/bin/main.cjs:425:62570)","code":422}
```

with such monorepo setup:
```
yarn.lock
package.json
   /packages
      /foo -> has listed dependency @acme/bar in foo/package.json
      /bar -> publishes @acme/bar package
```

`@acme/bar` does not exist in root `yarn.lock`, resulting with the above error.

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
