### ISSUE TITLE
Crash in Bitbucket pipeline /bin/sh: git: not found

### ISSUE THREAD

**Issue by hazem-alabiad** [chromaui/chromatic-cli#728]
**Bug report**

I am following this tutorial to support Chromatic deployment on Bitbucket Pipeline as here https://www.chromatic.com/docs/bitbucket-pipelines
But the yarn chromatic .... command is failing with the following error 

```bash
Chromatic CLI v6.17.2
https://www.chromatic.com/docs/cli
Authenticating with Chromatic
    → Connecting to https://index.chromatic.com/
Authenticated with Chromatic
    → Using project token '********f4f0'
Retrieving git information
    → Command failed with exit code 127: git --version
/bin/sh: git: not found
✖ Failed to retrieve git information
Command failed with exit code 127: git --version
/bin/sh: git: not found
→ View the full stacktrace below
If you need help, please chat with us at https://www.chromatic.com/docs/cli for the fastest response.
You can also email the team at [support@chromatic.com](mailto:support@chromatic.com) if chat is not an option.
Please provide us with the above CLI output and the following info:
{
  "timestamp": "2023-03-22T18:25:26.379Z",
  "sessionId": "da1d375f-5758-40fb-ab6d-11aa5edc63b0",
  "nodePlatform": "linux",
  "nodeVersion": "18.14.2",
  "packageName": "chromatic",
  "packageVersion": "6.17.2",
  "flags": {
    "projectToken": [
      "$CHROMATIC_PROJECT_TOKEN"
    ],
    "zip": true,
    "onlyChanged": "",
    "exitZeroOnChanges": "",
    "outputDir": [],
    "storybookBuildDir": [],
    "externals": [],
    "onlyStoryFiles": [],
    "onlyStoryNames": [],
    "untraced": [],
    "interactive": true,
    "appCode": []
  },
  "buildScript": "build-storybook",
  "exitCode": 0,
  "exitCodeKey": "OK",
  "errorType": "Error",
  "errorMessage": "✖ Failed to retrieve git information"
}
Error: ✖ Failed to retrieve git information
Command failed with exit code 127: git --version
/bin/sh: git: not found
    at e.exports (/opt/atlassian/pipelines/agent/build/node_modules/chromatic/bin/main.cjs:81:338657)
    at /opt/atlassian/pipelines/agent/build/node_modules/chromatic/bin/main.cjs:81:335835
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by winkerVSbecks** [comment]
Chromatic relies on git to find baselines. Please make sure that git is available in your Bitbucket pipeline.
