### ISSUE TITLE
Error: Unable to extract accountName with provided information.

### ISSUE THREAD

**Issue by jiheon788** [chromaui/chromatic-cli#782]
For chromatic distribution, the following commands were used. I get an error that didn't exist before, but I don't know what it means. There is no problem with the local storybook.

```
npx chromatic --project-token <my-project-token>
```

```

√ Authenticated with Chromatic
    → Using project token '****************71dc'
  √ Retrieved git information
    → Commit '60efcb2' on branch 'v2'; found 1 parent build
  √ Collected Storybook metadata
    → ; no supported addons found
  √ Initialized build
    → Build 5 initialized
  √ Storybook built in 37 seconds
    → View build log at C:\Users\******************\build-storybook.log
  √ Publish complete in 23 seconds
    → View your Storybook at ******************
  × Verifying your Storybook
    → Failed to publish build
    Test your stories

✖ Failed to extract stories from your Storybook
This is usually a problem with your published Storybook, not with Chromatic.

Build and open your Storybook locally and check the browser console for errors.
Visit your published Storybook at https://******************.chromatic.com
The following error was encountered while running your Storybook:

Error: page.evaluate: Error: Unable to extract accountName with provided information.
    at getAccountNameFromUrl (https://******************.chromatic.com/281.c9f9a55d.iframe.bundle.js:1:269076)
    at new StorageClient (https://******************.chromatic.com/281.c9f9a55d.iframe.bundle.js:1:333824)
    at new BlobServiceClient (https://******************.chromatic.com/281.c9f9a55d.iframe.bundle.js:1:519116)
    at new ImagoAzureStorage (https://******************.chromatic.com/281.c9f9a55d.iframe.bundle.js:1:535323)
    at ./src/Page/IconPage.stories.tsx (https://******************.chromatic.com/Page-IconPage-stories.ffc59406.iframe.bundle.js:1:3843)
    at __webpack_require__ (https://******************.capture.chromatic.com/runtime~main.5ab00efa.iframe.bundle.js:1:387)
    at https://******************.chromatic.com/main.0dfceccd.iframe.bundle.js:1:25142
    at async StoryStore.importFn (https://******************.chromatic.com/main.0dfceccd.iframe.bundle.js:1:28433)
```

**Comment by jiheon788** [comment]
I will find the source of the problem and close the issue. It was a personal reason. I'm sorry to bother you

**Comment by jiheon788** [comment]
I will find the source of the problem and close the issue. It was a personal reason. I'm sorry to bother you
