### ISSUE TITLE
Build fails if showSignature = true under [log] in .gitconfig

### ISSUE THREAD

**Issue by rcoyner** [chromaui/chromatic-cli#806]
**Bug report**

The build fails with the following _.gitconfig_ setting:

```
[log]
    showSignature = true
```

and emits the following error:

```

Error: ✖ Failed to initialize build
HTTPClient failed to fetch https://index.chromatic.com/graphql, got 400/Bad Request
    at retries (/src/pwa/node_modules/.pnpm/chromatic@6.24.1/node_modules/chromatic/dist/chunk-E44ZGXJS.js:54:10146)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retries (/src/pwa/node_modules/.pnpm/chromatic@6.24.1/node_modules/chromatic/dist/chunk-E44ZGXJS.js:130:7631)
    at async Xpr (/src/pwa/node_modules/.pnpm/chromatic@6.24.1/node_modules/chromatic/dist/chunk-E44ZGXJS.js:421:402)
    at async fV.task (/src/pwa/node_modules/.pnpm/chromatic@6.24.1/node_modules/chromatic/dist/chunk-E44ZGXJS.js:183:32055)
```

Enabling _--debug_ shows:

```
{"body":"{\"errors\":[{\"message\":\"Variable \\\"$input\\\" got invalid value \\\"gpg: Signature made Mon Aug 28 21:51:00 2023 PDT\\\\ngpg: ........ at \\\"input.commit\\\"; Expected type \\\"Hexadecimal\\\". Value is not a valid hexadecimal value: gpg: Signature made Mon Aug 28 21:51:00 2023 PDT\\ngpg: ........\",\"locations\":[{\"line\":2,\"column\":34}],\"extensions\":{\"code\":\"BAD_USER_INPUT\"}}]}\n"} HTTPClient failed to fetch https://index.chromatic.com/graphql, got 400/Bad Request
```

The workaround was straight-forward -- just turning the **showSignature** config to _false_. Not a big issue but wanted to flag.

**Comment by ghengeveld** [comment]
Hi Ryan,

That makes sense. We run `git log` under the covers and use the result (commit hashes, normally) for baseline calculations. Seems like we need to trim the gpg signature if we get one. 

Do you really need that showSignature option or are you happy to turn it off for the time being?

**Comment by rcoyner** [comment]
I can work around it so don't mind me!

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
