### ISSUE TITLE
Cannot read properties of undefined (reading 'isStoryMissing')

### ISSUE THREAD

**Issue by pietrofxq** [chromaui/chromatic-cli#818]
**Bug report**

I have two storybook tests that are failing in chromatic. The stack trace is related to chromatic playwright code:

```
page.evaluate: TypeError: Cannot read properties of undefined (reading 'isStoryMissing')
    at checkStoryMissing (eval at evaluate (:192:30), <anonymous>:1:64)
    at UtilityScript.evaluate (<anonymous>:194:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at ChromeRenderer.renderSpec (/opt/capture/src/chromatic-lib/capture/playwright-renderer/playwrightRenderer.js:734:25)
    at ChromeRenderer.renderSnapshot (/opt/capture/src/chromatic-lib/capture/playwright-renderer/playwrightRenderer.js:441:21)
    at ChromeRenderer.captureSpecs (/opt/capture/src/chromatic-lib/capture/playwright-renderer/playwrightRenderer.js:313:9)
    at ChromeRenderer.executeWithCallback (/opt/capture/src/chromatic-lib/capture/playwright-renderer/playwrightRenderer.js:101:14)
    at Capture.execute (/opt/capture/src/chromatic-lib/capture/capture.js:282:5)
    at FargateWorker.processJob (/opt/capture/src/worker.ts:258:7)
    at FargateWorker.handleJob (/opt/capture/src/worker.ts:137:7)
    at FargateWorker.run (/opt/capture/src/worker.ts:50:9)
    at start (/opt/capture/src/index.ts:33:5)
```

Visiting the storybook in chromatic the error does not show up. The component is rendered correctly for a few seconds and then a 500 page shows up:

<img width="835" alt="image" src="https://github.com/chromaui/chromatic-cli/assets/6238029/3544c28c-e251-4f18-9645-dfd3e719869b">

**Comment by winkerVSbecks** [comment]
@pietrofxq if this is still an issue, please reach out via support and we'll be able to help you better: https://www.chromatic.com/docs/support/
