### ISSUE TITLE
Chromatic fails with "sentinel" error after upgrading to 10.3.0

### ISSUE THREAD

**Issue by yngvebn** [chromaui/chromatic-cli#891]
Perhaps related to this: https://github.com/chromaui/chromatic-cli/pull/878

We use `npx chromatic@latest` in our build script, and it failed when running a build with 10.3.0. Works fine with 10.2.2

**Bug report**

A clear and concise description of what the bug is. Include screenshots if you can, but be aware this is a public medium. If you need to share private information, please contact the Chromatic support team.

Finalizing upload fails with the following stack trace

```
Publishing your built Storybook
    â†’ Finalizing upload
    â†’ Sentinel file not present.
[15:56:37] :		 [Publish Chromatic] 
Ã— Failed to publish your built Storybook
Sentinel file not present.
â†’ View the full stacktrace below
[15:56:37]W:		 [Publish Chromatic] 
If you need help, please chat with us at https://www.chromatic.com/docs/cli for the fastest response.
You can also email the team at support@chromatic.com if chat is not an option.
[15:56:37]W:		 [Publish Chromatic] 
Please provide us with the above CLI output and the following info:
{
  "timestamp": "2024-01-16T14:56:37.307Z",
  "sessionId": "f25cc764-4ef5-446d-a0e9-8b19b60cb685",
  "gitVersion": "2.36.1.windows.1",
  "nodePlatform": "win32",
  "nodeVersion": "20.9.0",
  "packageManager": "npm",
  "packageManagerVersion": "10.1.0",
  "packageName": "chromatic",
  "packageVersion": "10.3.0",
  "storybook": {
    "viewLayer": null,
    "version": null,
    "addons": [],
    "builder": null
  },
  "flags": {
    "storybookBuildDir": [
      "./storybook-static"
    ],
    "onlyChanged": "",
    "autoAcceptChanges": "*master",
    "storybookBaseDir": "src/Rikstoto.Toto",
    "exitOnceUploaded": "",
    "exitZeroOnChanges": "",
    "zip": true,
    "untraced": [
      "@codegen/**/*.*",
      "**/preview.ts",
      "**/toto-router-link.module.ts",
      "**/modal.module.ts",
      "**/components.module.ts",
      "**/docs/*.mdx"
    ],
    "externals": [
      "**/styles/global/base/variables/**.scss"
    ],
    "branchName": "9076/head",
    "outputDir": [],
    "onlyStoryFiles": [],
    "onlyStoryNames": [],
    "fileHashing": true,
    "interactive": true,
    "appCode": []
  },
  "configuration": {},
  "exitCode": 0,
  "exitCodeKey": "OK",
  "errorType": "Error",
  "errorMessage": "Ã— Failed to publish your built Storybook",
  "build": {
    "id": "65a68f0dc3b46d15dd135aeb",
    "number": 9489
  }
}
[15:56:37]W:		 [Publish Chromatic] 
Error: Ã— Failed to publish your built Storybook
Sentinel file not present.
    at Hqt.retries (C:\Windows\System32\config\systemprofile\AppData\Local\npm-cache\_npx\7d79bcd8fb3382c4\node_modules\chromatic\dist\chunk-FEQKHR2Z.js:1339:59806)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async pfi (C:\Windows\System32\config\systemprofile\AppData\Local\npm-cache\_npx\7d79bcd8fb3382c4\node_modules\chromatic\dist\chunk-FEQKHR2Z.js:1347:1022)
    at async wW.task (C:\Windows\System32\config\systemprofile\AppData\Local\npm-cache\_npx\7d79bcd8fb3382c4\node_modules\chromatic\dist\chunk-FEQKHR2Z.js:615:24596)
```

**Comment by thafryer** [comment]
Hi @yngvebn! I'm sorry for not getting back to you sooner. We resolved the issue of publishing storybooks. By updating the latest version, you should be squared away!

**Comment by yngvebn** [comment]
Thanks, @thafryer! We've just been using the working version, but now we can update 😊
