### ISSUE TITLE
Take snapshots tries to build-storybook but fails

### ISSUE THREAD

**Issue by jeremydrichardson** [chromaui/chromatic-cli#996]
**Bug report**

I'm trying to use the _Take snapshots_ feature in Storybook. When I click on the _Take snapshots_ button in the _Visual Tests_ tab of my local Storybook, it attempts to run a build but the build fails. The Chromatic snapshot then fails because it says _Invalid Storybook build at ..._.

I looked through the `chromatic.log` file and found this command:
```
npm run build-storybook -- --output-dir /var/folders/sm/zwkg3_xs4l5ch_c4x5c1_1_w0000gq/T/chromatic--32956-oMzUyWmMULxp
```

So I enabled the Storybook log and found the following error in `build-storybook.log`:
```
> workshop@5.0.0 build-storybook
> storybook build --output-dir /var/folders/sm/zwkg3_xs4l5ch_c4x5c1_1_w0000gq/T/chromatic--32956-oMzUyWmMULxp

@storybook/cli v8.1.5

info => Cleaning outputDir: ../../../../../../var/folders/sm/zwkg3_xs4l5ch_c4x5c1_1_w0000gq/T/chromatic--32956-oMzUyWmMULxp
info => Loading presets
info => Building manager..
info => Manager built (106 ms)
info => Building preview..
[36mvite v5.2.11 [32mbuilding for production...[36m[39m
transforming...
[32m✓[39m 369 modules transformed.
=> Failed to build the preview
RollupError: Expression expected
    at getRollupError (file:///Users/userx/Sites/mm-ui-components/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at ParseError.initialise (file:///Users/userx/Sites/mm-ui-components/node_modules/rollup/dist/es/shared/node-entry.js:11332:28)
    at convertNode (file:///Users/userx/Sites/mm-ui-components/node_modules/rollup/dist/es/shared/node-entry.js:13082:10)
    at convertProgram (file:///Users/userx/Sites/mm-ui-components/node_modules/rollup/dist/es/shared/node-entry.js:12399:12)
    at Module.setSource (file:///Users/userx/Sites/mm-ui-components/node_modules/rollup/dist/es/shared/node-entry.js:14243:24)
    at async ModuleLoader.addModuleSource (file:///Users/userx/Sites/mm-ui-components/node_modules/rollup/dist/es/shared/node-entry.js:18896:13)
```

Funny thing is if I run that same command manually from the command line it complete fine.
```
npm run build-storybook -w ./packages/workshop -- --output-dir /var/folders/sm/zwkg3_xs4l5ch_c4x5c1_1_w0000gq/T/chromatic--32956-oMzUyWmMULxp
```

The only thing that might be unique about my setup is that we're running Storybook in a monorepo. Not sure if that would have an effect on Rollup having an error.

Thanks

**Comment by cgbl-90** [comment]
hey @jeremydrichardson can you use our in-app chat to get in touch or [email us](mailto:support@chromatic.com)? 
Can you try to run a new build with the `--debug` flag and share the output? Thank you!

**Comment by jeremydrichardson** [comment]
Posted this in wrong repo. Here is the new issue - https://github.com/chromaui/addon-visual-tests/issues/318
